### ISSUE TITLE
Feature Request: Generate alternate feed types.

### ISSUE THREAD

**Issue by drcreek** [ghing/sqs-event-list#1]
Is it (I'm a n00b who is expecting a no.) possible to add the ability for this to generate an iCal feed so users can subscribe to the entire calendar and not just single events?

Long shot I know but worth the try.

Cheers.

DM

**Comment by ghing** [comment]
Unfortunately this isn't possible because of the nature of how iCal and client-side JavaScript works.  This plugin (sqs-event-list) transforms existing data to display on an HTML page.  It can't put that transformed data at a URL, which is what you'd want for an iCal feed to work.

**Comment by drcreek** [comment]
sorry, duh. Of course. The pages need to be actually loaded to run the javascript.

Sorry. total brain fart.

Cherrs anyway.

DM
